[simulation]
nx = 50
ny = 50
nz = 50
tspan_start = 0.0
tspan_end = 10.0
dt = 0.1

[eos]
K = 100.0
gamma = 2.0
P_c = 100.0

[magnetic]
B0 = 1e12
alpha = 0.5
beta_init = 0.01

[diffusion]
Î· = 1e-4
r_min = 1.0
r_max = 20.0
N = 200

[amr]
refinement_levels = 10
refine_threshold = 1.2e15
coarsen_threshold = 1.0e15
min_grid_spacing = 5.0

[parallel]
nprocs = 4

[i/o]
output_directory = "./output"
checkpoint_interval = 1000  # in simulation steps
